packages:
  - packages/*

overrides:
  '@babel/core@<=7.29.0': ^7.29.1
  "@babel/plugin-transform-modules-systemjs@>=7.12.0 <=7.29.3": ^7.29.4
  "axios@>=1.0.0 <1.15.2": ">=1.15.2"
  "bfj@<9.1.3": ~9.1.3
  "brace-expansion@>=5.0.0 <5.0.6": ">=5.0.6"
  esbuild@>=0.27.0 <0.28.1: ^0.28.1
  "fast-uri@<=3.1.1": ">=3.1.2"
  "follow-redirects@<1.15.6": ~1.16.0
  "glob@<10.5.0": ~10.5.0
  "hono@<4.12.25": ">=4.12.25"
  http-proxy-middleware@<3.0.6: ^3.0.6
  "ip-address@<=10.1.0": ">=10.1.1"
  "minimatch@>=3.0.0 <3.1.4": 3.1.4
  "minimatch@>=9.0.0 <9.0.6": ^10.2.3
  "nth-check@<2.0.1": ~2.0.1
  "picomatch@>4.0.0": ^4.0.4
  "piscina@<5.1.5": ^5.1.5
  qs@>=6.11.1 <=6.15.1: ^6.15.2
  sass: 1.101.0
  "serialize-javascript@<=7.0.2": 7.0.3
  "tar@<=7.5.10": ~7.5.11
  tmp@<0.2.7: ^0.2.7
  "underscore@<=1.13.7": 1.13.8
  uuid@<11.1.1: ^11.1.1
  vite: 7.3.6
  "webpack-dev-server@<5.2.5": ">=5.2.5"
  "ws@>=8.0.0 <8.20.1": ">=8.20.1"

allowBuilds:
  "@parcel/watcher": true
  core-js: true
  esbuild: true
  inferno: true
  lmdb: true
  msgpackr-extract: true
  unrs-resolver: true

catalogs:
  angular:
    devextreme-angular: ~26.1.3
    "@angular-devkit/build-angular": ^22.0.3
    "@angular-devkit/architect": ^0.2200.0
    "@angular-devkit/schematics": ^22.0.0
    "@angular/animations": ^22.0.2
    "@angular/build": ^22.0.3
    "@angular/cdk": ^22.0.2
    "@angular/cli": ^22.0.3
    "@angular/common": ^22.0.2
    "@angular/compiler": ^22.0.2
    "@angular/compiler-cli": ^22.0.2
    "@angular/core": ^22.0.2
    "@angular/forms": ^22.0.2
    "@angular/platform-browser": ^22.0.2
    "@angular/platform-browser-dynamic": ^22.0.2
    "@angular/platform-server": ^22.0.0
    "@angular/router": ^22.0.2
    "@angular-eslint/builder": ^21.4.0
    "@angular-eslint/eslint-plugin": ^21.4.0
    "@angular-eslint/eslint-plugin-template": ^21.4.0
    "@angular-eslint/schematics": ^21.4.0
    "@angular-eslint/template-parser": ^21.4.0
    "typescript": ~6.0.3
    "zone.js": ~0.16.2
