name: Lint

on:
  push:
  pull_request:

jobs:
  lint-project:
    strategy:
      fail-fast: false
      matrix:
        PROJECT: [ angular, react, vue, js, html, css ]

    runs-on: ubuntu-latest
    name: Lint ${{ matrix.PROJECT }}

    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Lint applications
      run: pnpm run lint-${{ matrix.PROJECT }}

    - name: Archive artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: test-results.xml
